# SOCKS5代理服务器配置
listen: 0.0.0.0
http_server: http://127.0.0.1:8080
# 认证方法配置:
# 0 = 无认证 (NoAuthenticationRequired)
# 2 = 用户名密码认证 (AccountPasswordAuthentication)
# 可以配置多个认证方法，服务器会按优先级选择
auth_list: [ 2 ]  # 优先用户名密码认证，其次无认证

